services:
  llservicios:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llservicios
    volumes:
      - .:/var/www/html
    environment:
      DB_HOST: host.docker.internal # Apunta al servicio MySQL en el host
      DB_PORT: 3306
      DB_DATABASE: llservicios
      DB_USERNAME: root
      DB_PASSWORD: secret
    ports:
      - "9000" # PHP-FPM escuchando en este puerto para que Nginx lo use
    command: >
      sh -c "chown -R www-data:www-data /var/www/html &&
             chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache &&
             php-fpm"
