services:
  llservicios:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llservicios
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000" # PHP-FPM escuchando en este puerto para que Nginx lo use

