services:
  llservicios:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llservicios
    volumes:
      - .:/var/www/html
    ports:
      - "8081:8081" # PHP-FPM escuchando en este puerto para que Nginx lo use

